version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Running PRISMA database scripts"
      - npx prisma migrate deploy
  build:
    commands:
      - npm run build
  post_build:
    commands:
        - cp -R node_modules/dist/node_modules
artifacts:
  files:
    - '**/*'
