services:
  database:
    image: postgres:16
    container_name: recy-database
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - recy-network

  backend:
    build: .
    container_name: recy-backend
    restart: always
    ports:
      - '80:80'
    depends_on:
      - database
      - redis
    env_file:
      - .env
    networks:
      - recy-network

  redis:
    image: redis:latest
    container_name: recy-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - recy-network

volumes:
  postgres-volume:
    external: false

networks:
  recy-network:
    external: false
